### ISSUE TITLE
문제를 Contest 단위로 가져오기

### ISSUE THREAD

**Issue by Sabro98** [Sabro98/jcode-jota#16]
현재는 Contest에 상관 없이 등록된 문제를 모두 가져오는 중임

이를 Contest 단위로 즉, **다른 contest에 있는 유저는 다른 문제 리스트를 보도록** 설정을 할 필요가 있어보임.

**Comment by jihyeonhur** [comment]
안녕하세요. 허지현입니다. 해당 주제를 진행하고 싶습니다!

**Comment by Sabro98** [comment]
안녕하세요, Issue에 대한 관심 감사합니다.

user, contest 등의 정보를 얻기 위한 API는 Jota에 있습니다.

하지만 extension 에서 Jota API를 호출하는 부분이 많기 때문에 이를 하나의 파일로 통합하는 작업을 진행중 입니다.
관련 이슈는 #14 에서 확인할 수 있습니다.

위 작업이 완료된 후 현재 Issue에 대한 작업을 진행하면 좋을것같습니다.

감사합니다.

**Comment by jihyeonhur** [comment]
알겠습니다! 그러면 우선 #18 이슈부터 해결해보도록 하겠습니다.
감사합니다.
