### ISSUE TITLE
제출 결과를 누르면 redirect 하도록 설정

### ISSUE THREAD

**Issue by Sabro98** [Sabro98/jcode-jota#17]
vscode API 에서 ShowMessageBox를 클릭하면 **다른 곳으로 이동** (ex, JOTA의 결과 페이지)할 수 있는 기능이 존재하는지 확인 필요

만약, 가능하다면 이를 적용시키고 상세 결과를 보도록 redirect 시킬 필요가 있음.

**Comment by jihyeonhur** [comment]
안녕하세요. 허지현 입니다. 해당 주제를 진행하고 싶습니다!

**Comment by Sabro98** [comment]
안녕하세요.

해당 주제를 잘 부탁합니다.

가능하다는게 확인되면 알려주신 후 바로 수정을 하면 됩니다.
만약, 불가능하다면 안된다는 사실을 알려주시기만 하면 됩니다.

감사합니다.

**Comment by jihyeonhur** [comment]
![image](https://user-images.githubusercontent.com/67954861/141774960-bb6e902e-ff31-44fe-82bd-ad8174ad93bd.png)

ShowMessageBox에 버튼을 넣어서 해당 버튼을 누르면 원하는 웹페이지로 바로 이동할 수 있는 기능을 찾았습니다!
임시로 특정 문제의 결과 페이지를 url로 넣고, 버튼을 눌러봤습니다.  
그 결과, JOTA로 이동이 되어 로그인 화면이 뜨고, 로그인을 하면 바로 결과 페이지가 뜨는 것을 확인하였습니다.
그리고 만약 웹페이지 로그인을 이미 해둔 상태라면, 로그인 필요없이 바로 결과 페이지가 뜨는 것을 확인하였습니다.

채점 후 jota에서 해당 문제 결과 페이지의 url을 전달 받을 수 있다면 해당 이슈를 해결할 수 있습니다. 만약 불가능 하다면,
결과 페이지의 url이 "(jota페이지 주소)/submission/(고유한 숫자)" 이고, 뒤에 고유한 숫자만 달라진다는 것을 활용하면 됩니다.
뒤에 고유한 숫자는 해당 contest에 제출된 총 문제수로 예상이 되므로,
해당 contest에 해당 문제가 몇 번째로 제출 되었는지를 알 수 있다면 해결할 수 있을 것이라고 생각합니다.

바로 수정을 진행하도록 하겠습니다! 감사합니다.

**Comment by Sabro98** [comment]
해당 기능이 있다니 다행이네요, 감사합니다.

현재 submit의 결과로 Jota에 대한 URL이 같이 오도록 수정을 하였습니다.

문제의 count를 할 필요 없이 해당 버튼과 URL을 연결해주는 방향으로 진행하면 좋을것 같습니다.
