### ISSUE TITLE
비밀번호 입력시 보안 기능 추가

### ISSUE THREAD

**Issue by jihyeonhur** [Sabro98/jcode-jota#18]
로그인을 위해 비밀번호를 입력할 때, '******' 이런식으로 입력이 되는 기능을 추가하는 건 어떨까요?

그리고 원할 때에는 입력하는 문자를 볼 수 있도록 **버튼으로 보안 기능 on/off**가 되도록 하면 좋을 것 같습니다!

**Comment by Sabro98** [comment]
안녕하세요.

해당 기능은 좋다고 생각합니다.

on/off가 가능할지 모르겠지만, '******' 까지는 가능하다고 생각합니다.
on/off가 불가능하다면 알려주시고, 가능하다면 이 기능까지 넣으면 될것같습니다.

감사합니다.

**Comment by jihyeonhur** [comment]
inputbox에 on/off 할수있는 버튼을 붙이는 기능이 없는 것 같습니다ㅠㅠ
그래서 비밀번호 입력시 '*******' 형식으로 입력되도록 하는 기능만 추가했습니다.
