### ISSUE TITLE
window환경에서 실행 시, 채점결과 기록에 문제

### ISSUE THREAD

**Issue by jihyeonhur** [Sabro98/jcode-jota#4]
window에서 실행할 때, result 폴더에 저장되어야하는
채점결과 + 소스코드가 저장되지 않는 문제가 있습니다.

**Comment by Sabro98** [comment]
아 좋은 지적 감사합니다.

혹시 이 문제가 윈도우에서 저장 경로를 지정하는것과 연관이 있나요?
만약 연관이 있다면 윈도우에서 save path 지정해주는 문제만 해결하면 될것같습니다.

**Comment by Sabro98** [comment]
해결하였습니다.
문제는 저장할 때 들어가는 ':' 기호때문이였네요
