### ISSUE TITLE
로그인 기능 추가

### ISSUE THREAD

**Issue by jihyeonhur** [Sabro98/jcode-jota#8]
현재 코드 제출 전, 학번만 입력받는 것으로 구현이 되어있는데

학번, 비밀번호를 모두 입력받아 로그인 후, 코드를 제출할 수 있으면 보안상 더 좋을 것이라고 생각됩니다!

학번만 입력받으면 다른 사람의 학번으로 잘못 제출하는 일이 생길 수 있습니다.

학번과 비밀번호를 입력받아서 jota나 jcloud에 회원가입되어있는 정보와 비교한 후, 일치한다면 로그인이 되는 기능을 추가하면 어떨까요?

**Comment by Sabro98** [comment]
안녕하세요, 좋은 Issue 감사합니다.  

해당 기능은 extension 설계에서도 고려를 했었고, 완성도를 높히기 위해 필수적인 기능이라 생각합니다.

이는 본인 인증을 하는 단계로 생각할 수 있습니다. 이를 해결하기 위한 2가지 방법을 생각해보면
  
1. JOTA로 직접 로그인
이 방식은 extension으로 해결하기는 어려울것같고, JOTA에 로그인 관련된 API 등이 있는지 살펴볼 필요가 있어보입니다. 
해당 API를 사용해서 통신을 하는 방식으로 해결하는게 괜찮아 보입니다.

2. JCloud의 인스턴스 정보 활용
이 방식이 더 괜찮은 방식으라고 생각합니다. 
JCode를 사용하기 위해서는 필수적으로 인스턴스를 생성해야하고, 이 인스턴스는 고유의 정보가 어딘가에 있을것이라 생각합니다. 이를 잘 찾아서 활용하면 좋은 결과가 나올것이라 기대합니다.  

이에 대해서는 어떻게 생각하시나요?

**Comment by Sabro98** [comment]
또한 이 문제는 #1 도 고려를 할 필요가 있어보입니다.

제출자의 정보를 변경을 해도 되지만,
대리 제출 등의 문제를  방지하기 위해 로그인에 성공하면 그 정보를 바꿀 수 없도록 하는것도 하나의 방법이라 생각합니다.

**Comment by jihyeonhur** [comment]
의견 감사합니다! 우선 JCloud의 인스턴스 정보를 얻어올 수 있는 방법에 대해 찾아보도록 하겠습니다.

로그인 구현을 마치고, 로그인을 성공하면 그 정보를 바꿀 수 없도록 하는 기능도 추가하면 좋을 것 같습니다.

우선 #2 issue 해결 후, 진행해보도록 하겠습니다.
방향이 잡히면 다시 말씀드리겠습니다. 감사합니다!

**Comment by Sabro98** [comment]
Jota에 API를 추가하고, 로그인 기능을 추가하였습니다.
